---
- name: Use redhat sys role to Configure Storage
  hosts: webservers
    # ignore_errors: true
  roles:
    - name: redhat.rhel_system_roles.storage
      # Similiar to volume group in rhel 8
      storage_pools:
        - name: vg_web
          disks:
            - /dev/vdb
          volumes:
            - name: lv_content
              size: "128 MiB"
              mount_point: "/var/www/html/content"
              fs_type: xfs
              state: present
            - name: lv_uploads
              size: "256 MiB"
              fs_type: xfs
              mount_point: "/var/www/html/uploads"
              state: present
      # Similiar to logical volume
      # storage_volumes:
      #   - name: images
      #     type: disk
      #     disks: ["mpathc"]
      #    mount_point: /opt/images
      #    fs_label: images

...
