---
storage_pools:
- name: apache-vg
  disks:
  - vdb
  type: lvm
  volumes:
  - name: content-lv
    size: "64 MiB"
    fs_type: xfs
    mount_point: /var/www
    state: present
  - name: logs-lv
    size: "128 MiB"
    fs_type: xfs
    mount_point: /var/log/httpd
    state: present

