---
- name: Install and configure web service
  hosts:
    - server[a-d].lab.example.com

  tasks:
    - name: Configure HTTPD
      ansible.builtin.import_tasks: tasks/web_tasks.yml
    - name: Configure Firewall
      ansible.builtin.import_tasks: tasks/firewall_tasks.yml
   
  handlers:
    - name: restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
